services:
  postgres-db:
    container_name: ModBPractice
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5432:5432"